## Exercicis Mòdul M7 - Pandas
#### *Jordi Calmet Xartó - IT Academy*

### M7 T12
En aquest exercici, treballaràs amb el dataset Udemy_courses.csv utilitzant la biblioteca Pandas de Python. Realitzaràs diverses tasques d’exploració, filtres, agrupacions i modificació de columnes.

Carrega el dataset Udemy_courses.csv i respon a les següents preguntes:

In [1]:
import pandas as pd

df = pd.read_csv('udemy_courses.csv')
df.head()

,id,title,url,is_paid,instructor_names,category,headline,num_subscribers,rating,num_reviews,instructional_level,objectives,curriculum
0,567828,The Complete Python Bootcamp From Zero to Hero...,https://www.udemy.com/course/complete-python-b...,True,"Jose Portilla, Pierian Training",Development,Learn Python like a Professional Start from t...,1976866,4.576494,521219,All Levels,You will learn how to leverage the power of Py...,"Course Overview, Auto-Welcome Message, Course ..."
1,1565838,The Complete 2024 Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Become a Full-Stack Web Developer with just ON...,1362586,4.679065,409793,All Levels,Build 16 web development projects for your por...,"Front-End Web Development, What You'll Get in ..."
2,2776760,100 Days of Code: The Complete Python Pro Boot...,https://www.udemy.com/course/100-days-of-code/,True,"Dr. Angela Yu, Developer and Lead Instructor",Development,Master Python by building 100 projects in 100 ...,1417942,4.698768,331803,All Levels,You will master the Python programming languag...,Day 1 - Beginner - Working with Variables in P...
3,625204,The Web Developer Bootcamp 2024,https://www.udemy.com/course/the-web-developer...,True,Colt Steele,Development,10 Hours of React just added. Become a Develop...,923815,4.673450,276723,All Levels,"The ins and outs of HTML5, CSS3, and Modern Ja...","Course Orientation, Welcome To The Course!, Jo..."
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,https://www.udemy.com/course/react-the-complet...,True,"Academind by Maximilian Schwarzmüller, Maximil...",Development,Dive in and learn React.js from scratch! Learn...,909848,4.638643,220051,All Levels,Learn React from the ground up and finish the ...,"Getting Started, Welcome To The Course!, What ..."

1. Exploració de dades:

- Quantes columnes té el CSV, i quants registres?
- Quantes columnes de tipus enter té? I quantes de tipus decimal?
- Quin és el nombre de reviews màxim? I el de subcribers?
- Quina és la mitjana del ràting?
- Com has trobat totes aquestes respostes?

In [2]:
df.info()

# 13 columnes
# 3691 registres
# 3 columnes de tipus enter
# 1 columna de tipus decimal

<class 'pandas.DataFrame'>
RangeIndex: 3691 entries, 0 to 3690
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   3691 non-null   int64
 1   title                3691 non-null   str
 2   url                  3691 non-null   str
 3   is_paid              3691 non-null   bool
 4   instructor_names     3691 non-null   str
 5   category             3691 non-null   str
 6   headline             3691 non-null   str
 7   num_subscribers      3691 non-null   int64
 8   rating               3691 non-null   float64
 9   num_reviews          3691 non-null   int64
 10  instructional_level  3691 non-null   str
 11  objectives           3691 non-null   str
 12  curriculum           3691 non-null   str
dtypes: bool(1), float64(1), int64(3), str(8)
memory usage: 349.8 KB

In [3]:
df.describe()
# Màxim Reviews: 521219
# Màxim Subscribers: 1976866
# Mitjana de Rating: 4.40

                 id  num_subscribers       rating    num_reviews
count  3.691000e+03     3.691000e+03  3691.000000    3691.000000
mean   2.440617e+06     3.497767e+04     4.400517    4057.146844
std    1.525736e+06     8.362672e+04     0.323876   17487.536933
min    8.082000e+03     7.920000e+02     2.177373     317.000000
25%    1.191903e+06     4.973000e+03     4.267311     507.000000
50%    2.165246e+06     1.155000e+04     4.474494     966.000000
75%    3.670089e+06     3.079600e+04     4.614150    2419.500000
max    6.185965e+06     1.976866e+06     5.000000  521219.000000

2. Filtres:

- Selecciona els cursos que tenen més de 100.000 subscriptors,
més d’un 4,7 de valoració i més de 90.000 ressenyes.
- Selecciona els cursos que tenen un "instructional level" de
principiants i que són de la categoria "Development".

In [4]:
df.loc[((df['num_subscribers'] > 100000) & (df['rating'] > 4.7) & (df['num_reviews'] > 90000)), ['id', 'title', 'num_subscribers', 'num_reviews', 'rating']]

,id,title,num_subscribers,num_reviews,rating
13,437398,Build Responsive Real-World Websites with HTML...,433995,109925,4.724851
17,1778502,iOS & Swift - The Complete iOS App Development...,392351,92291,4.708041

In [5]:
df.loc[(df['instructional_level'] == 'Beginner Level') & (df['category'] == 'Development'), ['id', 'title', 'instructional_level', 'category']]

,id,title,instructional_level,category
16,1187016,The Ultimate MySQL Bootcamp: Go from SQL Begin...,Beginner Level,Development
22,382002,C# Basics for Beginners: Learn C# Fundamentals...,Beginner Level,Development
31,1419182,SQL for Beginners: Learn SQL using MySQL and D...,Beginner Level,Development
33,903378,The Python Bible™ | Everything You Need to Pro...,Beginner Level,Development
42,1535678,Java Programming for Complete Beginners,Beginner Level,Development
...,...,...,...,...
3674,2618738,Fortran For Beginners,Beginner Level,Development
3681,2445302,Django with GraphQL,Beginner Level,Development
3685,4866490,2024 R Programming Bootcamp for Absolute Begin...,Beginner Level,Development
3688,5018456,Web Design Course for Beginners to Intermediate,Beginner Level,Development
3690,4100126,Salesforce Development Master Training for Beg...,Beginner Level,Development

3. Agrupacions:

- Mostra el nombre de cursos per categoria.
- Mostra la mitjana de valoració per "instructional level" i “is_paid”.

In [6]:
df['category'].value_counts()

category
Development    3691
Name: count, dtype: int64

In [7]:
df.groupby('instructional_level')[['rating']].mean()

                       rating
instructional_level
All Levels           4.405400
Beginner Level       4.385644
Expert Level         4.332760
Intermediate Level   4.417414

In [8]:
df.groupby('is_paid')[['rating']].mean()

           rating
is_paid
True     4.400517

In [9]:
df.groupby(['instructional_level', 'is_paid'])[['rating']].mean()

                               rating
instructional_level is_paid
All Levels          True     4.405400
Beginner Level      True     4.385644
Expert Level        True     4.332760
Intermediate Level  True     4.417414

4. Modificació de columnes:

- Afegir una columna nova al DataFrame anomenada “CursGran” que tingui com a valor True si la quantitat de subscriptors és més de 50.000 i False sinó.
- Crea un dataframe que NO contingui les últimes 6 columnes del dataframe original. Aquest nou dataframe guarda’l a una variable anomenada info_general.

In [10]:
def curs_es_gran(num_subs):
    return (num_subs > 50000)

df['CursGran'] = df['num_subscribers'].apply(curs_es_gran)
df[['id', 'title', 'num_subscribers', 'CursGran']]

,id,title,num_subscribers,CursGran
0,567828,The Complete Python Bootcamp From Zero to Hero...,1976866,True
1,1565838,The Complete 2024 Web Development Bootcamp,1362586,True
2,2776760,100 Days of Code: The Complete Python Pro Boot...,1417942,True
3,625204,The Web Developer Bootcamp 2024,923815,True
4,1362070,React - The Complete Guide 2024 (incl. Next.js...,909848,True
...,...,...,...,...
3686,689522,Data Visualization with MATLAB - Projects and ...,3522,False
3687,5246736,Advanced WordPress & Elementor 2024 | Build Dy...,2580,False
3688,5018456,Web Design Course for Beginners to Intermediate,27891,False
3689,1676620,D3.js in Action: Build 17 D3.js Data Visualiza...,3325,False
3690,4100126,Salesforce Development Master Training for Beg...,2360,False

In [11]:
df.shape

(3691, 14)

In [12]:
info_general = df.drop(df.columns[[8, 9, 10, 11, 12, 13]], axis=1)
info_general.columns

Index(['id', 'title', 'url', 'is_paid', 'instructor_names', 'category',
       'headline', 'num_subscribers'],
      dtype='str')

### M7 T13
La nostra empresa es dedica a realitzar anàlisis de dades hospitalaries, i un client ens ha sol·licitat una eina per identificar dades bàsiques dels hospitals de cada comunitat autònoma de forma automàtica.

Per això, cal crear una funció que rebi dos paràmetres:

- Un DataFrame amb informació d’hospitals (com el del fitxer hospitals.csv).
- El nom d’una comunitat autònoma (com a cadena de text).

La funció ha de retornar un diccionari amb les següents dades relacionades amb la comunitat autónoma indicada:

- Quantitat d’hospitals que hi ha a la comunitat autònoma
- Quantitat d’hospitals que hi ha a la comunitat autónoma que tenen més del 50% d’ocupació
- Indice_satifaccion màxim de la comunitat autónoma
- Indice_satifaccion mínim de la comunitat autònoma
- Total de llits a la comunitat autónoma
- Mitjana de l’index de satisfacció dels hospitals de la comunitat autònoma

Finalment, carrega el fitxer adjunt amb aquesta instrucció: data = pd.read_csv("arxiu csv", sep = ";", encoding = "latin-1") 
i executa la funció per a diverses comunitats autònomes i mostra els resultats obtinguts.

In [2]:
data = pd.read_csv("hospitals.csv", sep = ";", encoding = "latin-1")
data.head()

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
0,1,Hospital Universitario Torrecardenas,Almeria,Almeria,Andalucia,138.92,645,329,9.5,96.8
1,2,Hospital de Poniente,Almeria,Almeria,Andalucia,150.52,575,228,4.2,78.5
2,3,Hospital Universitario Puerta del Mar,Cadiz,Cadiz,Andalucia,496.80,834,32,6.4,81.5
3,4,Hospital de Jerez,Jerez de la Frontera,Cadiz,Andalucia,149.66,773,56,5.8,50.7
4,5,Hospital Universitario Reina Sofia,Cordoba,Cordoba,Andalucia,358.41,277,433,1.9,61.4

In [14]:
data.tail()

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
165,166,Hospital San Pedro,Logroño,La Rioja,La Rioja,457.88,944,104,3.4,89.4
166,167,Hospital Universitario de Ceuta,Ceuta,Ceuta,Ceuta,263.46,208,276,6.3,88.5
167,168,Hospital Comarcal de Melilla,Melilla,Melilla,Melilla,384.25,652,127,6.5,88.4
168,169,Fundacion Hospital Calahorra,Calahorra,La Rioja,La Rioja,54.92,126,182,2.3,54.8
169,170,Hospital General de La Rioja,Logroño,La Rioja,La Rioja,83.10,517,112,3.6,65.5

In [4]:
def dades_hospitals(dfh, comunitat):
    dicc_dades = {}

    # Quantitat d'hospitals a la comunitat autònoma
    num_hospitals = dfh.loc[dfh['comunidad_autonoma'] == comunitat, 'hospital_id'].count()
    dicc_dades['num_hospitals'] = int(num_hospitals)

    # Quantitat d'hospitals a la comunitat autònoma amb més del 50% d'ocupació
    num_h_ocupats = dfh.loc[(dfh['comunidad_autonoma'] == comunitat) & (dfh['porcentaje_ocupacion'] > 50.0), 'hospital_id'].count()
    dicc_dades['num_h_ocupats'] = int(num_h_ocupats)

    # Índex satisfacció màxim de la comunitat autònoma
    max_satisfaccio = dfh.loc[dfh['comunidad_autonoma'] == comunitat, 'indice_satisfaccion'].max().round(2)
    dicc_dades['max_satisfaccio'] = float(max_satisfaccio)

    # Índex satisfacció mínim de la comunitat autònoma
    min_satisfaccio = dfh.loc[dfh['comunidad_autonoma'] == comunitat, 'indice_satisfaccion'].min().round(2)
    dicc_dades['min_satisfaccio'] = float(min_satisfaccio)

    # Total de llits a la comunitat autònoma
    total_llits = dfh.loc[dfh['comunidad_autonoma'] == comunitat, 'num_camas'].sum()
    dicc_dades['total_llits'] = int(total_llits)

    # Mitjana de l'índex de satisfacció
    mitjana_satisfaccio = dfh.loc[dfh['comunidad_autonoma'] == comunitat, 'indice_satisfaccion'].mean().round(2)
    dicc_dades['mitjana_satisfaccio'] = float(mitjana_satisfaccio)

    return dicc_dades

print(dades_hospitals(data, 'Andalucia'))
print(dades_hospitals(data, 'Cataluña'))
print(dades_hospitals(data, 'Comunidad de Madrid'))

{'num_hospitals': 31, 'num_h_ocupats': 31, 'max_satisfaccio': 9.8, 'min_satisfaccio': 1.6, 'total_llits': 16201, 'mitjana_satisfaccio': 5.51}
{'num_hospitals': 16, 'num_h_ocupats': 16, 'max_satisfaccio': 7.3, 'min_satisfaccio': 1.1, 'total_llits': 8955, 'mitjana_satisfaccio': 4.93}
{'num_hospitals': 9, 'num_h_ocupats': 9, 'max_satisfaccio': 9.3, 'min_satisfaccio': 1.1, 'total_llits': 4409, 'mitjana_satisfaccio': 4.29}

### M7 T14
La nostra empresa está colaborant amb el colectiu de metges per veure quina càrrega de treball están patint. La idea es veure quins metges han de donar suport a més pacients i quins sembla que tenen menys persones a càrrec.

Per fer-ho, ens han proporcionat un conjunt de dades (hospitals.csv) que conté informació detallada sobre els hospitals del país.

Crea una funció en Python que rebi com a paràmetres:

- Un DataFrame amb dades d’hospitals.
- El nombre n d’hospitals que es volen obtenir com a resultat.

La funció ha de calcular, per a cada hospital la càrrega de treball dels metges, utilitzant la següent fórmula:

càrrega treball metge = num_llits /num_metges * percentatge ocupació

La funció ha de retornar els n hospitals amb més càrrega de treball per metge.

Executa la funció per obtenir 10 hospitals i després per obtenir-ne 20.

In [17]:
def carrega_hospitals(dfh, n):
    dfh['carga_medico'] = ((dfh['num_camas'] / dfh['num_medicos']) * dfh['porcentaje_ocupacion'] / 100).round(2)
    dfh = dfh.sort_values(by='carga_medico', ascending=False)
    # return dfh.head(n)
    return dfh.iloc[0:n, [1, 2, 10]]

carrega_hospitals(data, 10)

,nombre,localidad,carga_medico
66,Hospital de Sierrallana,Torrelavega,56.77
57,Hospital Doctor Jose Molina Orosa,Arrecife (Lanzarote),32.79
14,Hospital Universitario Virgen del Rocio,Sevilla,26.12
2,Hospital Universitario Puerta del Mar,Cadiz,21.24
104,Hospital de Tortosa Verge de la Cinta,Tortosa,18.46
15,Hospital Universitario Virgen Macarena,Sevilla,16.41
50,Hospital Mateu Orfila,Mao,15.77
5,Hospital Infanta Margarita,Cordoba,12.63
99,Hospital d'Olot i Comarcal de la Garrotxa,Olot,11.02
77,Hospital General Nuestra Señora del Prado,Talavera de la Reina,9.61

In [6]:
carrega_hospitals(data, 20)

,hospital_id,nombre,localidad,carga_medico
66,67,Hospital de Sierrallana,Torrelavega,56.77
57,58,Hospital Doctor Jose Molina Orosa,Arrecife (Lanzarote),32.79
14,15,Hospital Universitario Virgen del Rocio,Sevilla,26.12
2,3,Hospital Universitario Puerta del Mar,Cadiz,21.24
104,105,Hospital de Tortosa Verge de la Cinta,Tortosa,18.46
15,16,Hospital Universitario Virgen Macarena,Sevilla,16.41
50,51,Hospital Mateu Orfila,Mao,15.77
5,6,Hospital Infanta Margarita,Cordoba,12.63
99,100,Hospital d'Olot i Comarcal de la Garrotxa,Olot,11.02
77,78,Hospital General Nuestra Señora del Prado,Talavera de la Reina,9.61
165,166,Hospital San Pedro,Logroño,8.11
87,88,Complejo Asistencial de Zamora,Zamora,7.10
3,4,Hospital de Jerez,Jerez de la Frontera,7.00
130,131,Hospital da Costa,Burela,6.07
64,65,Hospital Universitario Marques de Valdecilla,Santander,5.82
26,27,Hospital de Antequera,Antequera,5.74
162,163,Hospital de Santa Marina,Bilbao,5.40
74,75,Hospital de Puerto Llano,Puerto Llano,5.25
121,122,Hospital de Zafra,Zafra,5.18
10,11,Hospital Universitario de Jaen,Jaen,4.86

## PER PRACTICAR MÉS

In [7]:
hospitals = pd.read_csv('hospitals.csv', sep = ";", encoding = "latin-1")
hospitals

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
0,1,Hospital Universitario Torrecardenas,Almeria,Almeria,Andalucia,138.92,645,329,9.5,96.8
1,2,Hospital de Poniente,Almeria,Almeria,Andalucia,150.52,575,228,4.2,78.5
2,3,Hospital Universitario Puerta del Mar,Cadiz,Cadiz,Andalucia,496.80,834,32,6.4,81.5
3,4,Hospital de Jerez,Jerez de la Frontera,Cadiz,Andalucia,149.66,773,56,5.8,50.7
4,5,Hospital Universitario Reina Sofia,Cordoba,Cordoba,Andalucia,358.41,277,433,1.9,61.4
...,...,...,...,...,...,...,...,...,...,...
165,166,Hospital San Pedro,Logroño,La Rioja,La Rioja,457.88,944,104,3.4,89.4
166,167,Hospital Universitario de Ceuta,Ceuta,Ceuta,Ceuta,263.46,208,276,6.3,88.5
167,168,Hospital Comarcal de Melilla,Melilla,Melilla,Melilla,384.25,652,127,6.5,88.4
168,169,Fundacion Hospital Calahorra,Calahorra,La Rioja,La Rioja,54.92,126,182,2.3,54.8
169,170,Hospital General de La Rioja,Logroño,La Rioja,La Rioja,83.10,517,112,3.6,65.5

### FILTRES:

In [8]:
# a) Mostra totes les dades dels hospitals que tenen entre 100 i 120 "num_camas".
hospitals[(hospitals['num_camas'] >= 100) & (hospitals['num_camas'] <= 120)]

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
34,35,Hospital Royo Villanova,Zaragoza,Zaragoza,Aragon,203.83,110,229,6.2,65.2
41,42,Hospital de Cabueñes,Gijon,Asturias,Asturias,100.27,111,123,9.4,91.1
56,57,Hospital General de Fuerteventura,Puerto del Rosario (Fuerteventura),Las Palmas,Islas Canarias,25.64,120,415,8.6,78.7
78,79,Complejo Asistencial de Avila,Avila,Avila,Castilla y Leon,186.93,110,311,5.1,56.4
98,99,Hospital de Figueres,Figueres,Girona,Cataluña,140.26,115,370,6.5,78.7
136,137,Hospital General Universitario Gregorio Marañon,Madrid,Madrid,Comunidad de Madrid,487.71,112,83,8.8,64.9

In [9]:
# b) Mostra els noms dels hospitals que estan a Barcelona - Catalunya.
hospitals[(hospitals['localidad'] == 'Barcelona') & (hospitals['comunidad_autonoma'] == 'Cataluña')]

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
89,90,Hospital Clinic de Barcelona,Barcelona,Barcelona,Cataluña,120.97,314,240,7.3,93.2
90,91,Hospital del Mar,Barcelona,Barcelona,Cataluña,312.25,754,406,4.3,75.1
91,92,Hospital Universitario Vall d'Hebron,Barcelona,Barcelona,Cataluña,496.44,279,109,1.1,89.9
95,96,Hospital de la Santa Creu i Sant Pau,Barcelona,Barcelona,Cataluña,303.46,946,468,5.2,53.1

In [10]:
# c) Mostra els 3 hospitals amb més "indice_satisfaccion" del grup d'hospitals de Madrid i Andalusia.
hospitals[hospitals['comunidad_autonoma'].isin(['Comunidad de Madrid', 'Andalucia'])].sort_values(by='indice_satisfaccion', ascending=False).head(3)

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
17,18,Hospital Universitario de Jerez,Jerez de la Frontera,Cadiz,Andalucia,232.89,805,456,9.8,68.7
22,23,Hospital de Alta Resolucion de la Costa Occide...,Lepe,Huelva,Andalucia,261.85,304,462,9.7,50.4
25,26,Hospital Costa del Sol,Marbella,Malaga,Andalucia,248.10,610,178,9.7,51.4

In [11]:
# d) Mostra els hospitals que comencen per lletra "C" i terminen per lletra "a".
hospitals[hospitals['nombre'].str.startswith('C') & hospitals['nombre'].str.endswith('a')]

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion
78,79,Complejo Asistencial de Avila,Avila,Avila,Castilla y Leon,186.93,110,311,5.1,56.4
81,82,Complejo Asistencial Universitario de Palencia,Palencia,Palencia,Castilla y Leon,217.95,599,189,2.3,55.8
83,84,Complejo Asistencial de Segovia,Segovia,Segovia,Castilla y Leon,206.91,610,188,8.9,76.7
87,88,Complejo Asistencial de Zamora,Zamora,Zamora,Castilla y Leon,204.16,967,126,6.7,92.5
124,125,Complejo Hospitalario Universitario de A Coruña,A Coruña,A Coruña,Galicia,149.38,791,269,5.4,84.6
153,154,Complejo Hospitalario de Navarra,Pamplona,Navarra,Navarra,142.34,450,457,8.0,74.4

### AGRUPACIONS:

In [13]:
# a) Mostra el "indice_satisfaccion" mig de cada comunitat autònoma i província de la taula "hospitals".
hospitals.groupby(['comunidad_autonoma','provincia'])['indice_satisfaccion'].mean().round(2)

comunidad_autonoma    provincia
Andalucia             Almeria                   6.50
                      Cadiz                     6.10
                      Cordoba                   3.80
                      Granada                   5.32
                      Huelva                    6.43
                      Jaen                      4.12
                      Malaga                    5.56
                      Sevilla                   6.12
Aragon                Huesca                    6.90
                      Teruel                    6.70
                      Zaragoza                  6.90
Asturias              Asturias                  7.38
Cantabria             Cantabria                 4.58
Castilla y Leon       Avila                     5.10
                      Burgos                    7.20
                      Leon                      6.60
                      Palencia                  2.30
                      Salamanca                 5.00
                      Segovia                   8.90
                      Soria                     8.90
                      Valladolid                4.65
                      Zamora                    6.70
Castilla-La Mancha    Albacete                  6.07
                      Ciudad Real               2.57
                      Cuenca                    9.30
                      Guadalajara               5.70
                      Toledo                    5.63
Cataluña              Barcelona                 5.20
                      Girona                    5.03
                      Lleida                    2.13
                      Tarragona                 6.52
Ceuta                 Ceuta                     6.30
Comunidad Valenciana  Alicante                  5.65
                      Castellon                 6.57
                      Valencia                  6.56
Comunidad de Madrid   Madrid                    4.29
Extremadura           Badajoz                   4.88
                      Caceres                   4.00
Galicia               A Coruña                  4.20
                      Lugo                      6.85
                      Ourense                   5.95
                      Pontevedra                6.52
Islas Baleares        Formentera                5.90
                      Ibiza                     1.70
                      Mallorca                  5.32
                      Menorca                   8.20
Islas Canarias        Las Palmas                7.28
                      Santa Cruz de Tenerife    6.88
La Rioja              La Rioja                  3.10
Melilla               Melilla                   6.50
Navarra               Navarra                   7.78
Pais Vasco            Alava                     4.55
                      Guipuzcoa                 5.68
                      Vizcaya                   7.65
Region de Murcia      Murcia                    4.87
Name: indice_satisfaccion, dtype: float64

In [14]:
# b) Mostra el "num_camas" total de cada comunitat autònoma.
hospitals.groupby('comunidad_autonoma')['num_camas'].sum().reset_index(name = 'Num_camas')

      comunidad_autonoma  Num_camas
0              Andalucia      16201
1                 Aragon       4661
2               Asturias       1980
3              Cantabria       3166
4        Castilla y Leon       5948
5     Castilla-La Mancha       4958
6               Cataluña       8955
7                  Ceuta        208
8   Comunidad Valenciana       6547
9    Comunidad de Madrid       4409
10           Extremadura       2805
11               Galicia       6164
12        Islas Baleares       3947
13        Islas Canarias       4858
14              La Rioja       1587
15               Melilla        652
16               Navarra       2617
17            Pais Vasco       6689
18      Region de Murcia       3790

In [14]:
# c) Mostra el "porcentaje_ocupacion" més petit de cada província de cada comunitat autònoma.
hospitals.groupby(['comunidad_autonoma','provincia'])['porcentaje_ocupacion'].min()

comunidad_autonoma    provincia
Andalucia             Almeria                   78.5
                      Cadiz                     50.7
                      Cordoba                   59.5
                      Granada                   50.7
                      Huelva                    50.4
                      Jaen                      54.7
                      Malaga                    51.4
                      Sevilla                   52.1
Aragon                Huesca                    62.0
                      Teruel                    73.8
                      Zaragoza                  52.8
Asturias              Asturias                  61.7
Cantabria             Cantabria                 75.6
Castilla y Leon       Avila                     56.4
                      Burgos                    75.9
                      Leon                      63.8
                      Palencia                  55.8
                      Salamanca                 95.3
                      Segovia                   76.7
                      Soria                     59.6
                      Valladolid                77.9
                      Zamora                    92.5
Castilla-La Mancha    Albacete                  58.3
                      Ciudad Real               52.9
                      Cuenca                    70.9
                      Guadalajara               98.5
                      Toledo                    67.2
Cataluña              Barcelona                 53.1
                      Girona                    78.7
                      Lleida                    72.6
                      Tarragona                 64.7
Ceuta                 Ceuta                     88.5
Comunidad Valenciana  Alicante                  50.6
                      Castellon                 55.1
                      Valencia                  65.6
Comunidad de Madrid   Madrid                    53.7
Extremadura           Badajoz                   67.9
                      Caceres                   66.8
Galicia               A Coruña                  83.6
                      Lugo                      56.3
                      Ourense                   60.8
                      Pontevedra                67.8
Islas Baleares        Formentera                65.6
                      Ibiza                     64.5
                      Mallorca                  50.8
                      Menorca                   70.6
Islas Canarias        Las Palmas                60.9
                      Santa Cruz de Tenerife    55.0
La Rioja              La Rioja                  54.8
Melilla               Melilla                   88.4
Navarra               Navarra                   69.8
Pais Vasco            Alava                     65.5
                      Guipuzcoa                 53.8
                      Vizcaya                   51.7
Region de Murcia      Murcia                    64.5
Name: porcentaje_ocupacion, dtype: float64

In [15]:
# d) Mostra quantes províncies i localitats té cada comunitat autònoma.
hospitals_prov = hospitals.groupby('comunidad_autonoma').agg({'provincia': 'nunique', 'localidad': 'nunique'})
hospitals_prov

                      provincia  localidad
comunidad_autonoma
Andalucia                     8         23
Aragon                        3          8
Asturias                      1          4
Cantabria                     1          3
Castilla y Leon               9         10
Castilla-La Mancha            5          9
Cataluña                      4         11
Ceuta                         1          1
Comunidad Valenciana          3          7
Comunidad de Madrid           1          4
Extremadura                   2          6
Galicia                       4         10
Islas Baleares                4          6
Islas Canarias                2          8
La Rioja                      1          2
Melilla                       1          1
Navarra                       1          3
Pais Vasco                    3          9
Region de Murcia              1          3

In [15]:
# e) Mostra les comunitats autònomes que tenen menys de 5 hospitals.
hospitals_cc = hospitals.groupby('comunidad_autonoma')['hospital_id'].count().reset_index(name = 'Num_hospitals')
hospitals_cc[hospitals_cc['Num_hospitals'] < 5]

   comunidad_autonoma  Num_hospitals
3           Cantabria              4
7               Ceuta              1
14           La Rioja              3
15            Melilla              1
16            Navarra              4